// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tzdvexxbfuoypaklbhmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6ZHZleHhiZnVveXBha2xiaG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4Mjk3ODcsImV4cCI6MjA1ODQwNTc4N30.BsLLgVl_A0RcHsiQBOYcsWKFbKYXw3-74RB1vClOy7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);